org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.51-beta
neo_version_range=[26.3.0.51-beta,)
java_version=25
junit_version=5.13.4
jcodec_version=0.2.5

mod_id=arkea
mod_name=Arkea
mod_version=0.1
mod_group_id=com.aryston.arkea
mod_license=Custom
mod_authors=Aryston
mod_url=https://github.com/arystonmc/Arkea
